---
sensor:
  name: "Battery Temperature"
  device:
    identifiers:
      - inverter
    manufacturer: "Deya LTD"
    model: "SUN-6K-SG03LP1-EU"
    name: "Hybryd Inverter"
    serial_number: "123456789"
  device_class: "temperature"
  enabled_by_default: "true"
  object_id: "inverter_battery_temperature"
  state_class: "measurement"
  state_topic: "homeassistant/sensor/inverter/state"
  unique_id: "inverter_battery_temperature"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.battery_temperature }}'
