---
sensor:
  name: "Battery State Of Charge"
  device:
    identifiers:
      - inverter
    manufacturer: "Deya LTD"
    model: "SUN-6K-SG03LP1-EU"
    name: "Hybryd Inverter"
    serial_number: "123456789"
  device_class: "battery"
  enabled_by_default: true
  object_id: "inverter_battery_soc"
  state_class: "measurement"
  state_topic: "homeassistant/sensor/inverter/state"
  unique_id: "inverter_battery_soc"
  unit_of_measurement: '%'
  value_template: '{{ value_json.battery_soc }}'
