---
sensor:
  device:
    identifiers:
      - inverter
    manufacturer: "Deya LTD"
    model: "SUN-6K-SG03LP1-EU"
    name: "Hybryd Inverter"
    serial_number: "123456789"
  name: "Overall State"
  device_class: "enum"
  enabled_by_default: true
  object_id: "inverter_overall_state"
  state_topic: "homeassistant/sensor/inverter/state"
  unique_id: "inverter_overall_state"
  value_template: '{{ value_json.overall_state }}'
